  
name: WebdriverIO - Webdriver - Examples - Sauce

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      
      # - name: Start SC
      #   uses: saucelabs/sauce-connect-action@v1
      #   with:
      #     username: ${{ secrets.SAUCE_USERNAME }}
      #     accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
      #     tunnelIdentifier: github-action-tunnel
      #     restUrl: https://eu-central-1.saucelabs.com/rest/v1
      #     scVersion: 4.6.4

      - name: Run tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BUILD_TAG: ${{github.repository}} - ${{github.run_number}}
        run: |
          echo "hi you"
          echo "$GITHUB_REPOSITORY - $GITHUB_RUN_NUMBER"
          echo 1
          echo $BUILD_TAG
          echo "hi you"
          npm run test.saucelabs.eu
